# Generated by Django 5.1.2 on 2024-10-27 09:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='subject_model',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200)),
                ('count_weeks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('count_lessons', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subjects',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='week_model',
            fields=[
                ('week_id', models.AutoField(primary_key=True, serialize=False)),
                ('week_num', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('avg_sleep', models.FloatField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('avg_phys_activity', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('lessons_visited', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('time_spent', models.FloatField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.subject_model')),
            ],
            options={
                'db_table': 'weeks',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('week_num', 'subject_id'), name='unique item in plant')],
            },
        ),
    ]
